name: .NET Build and Test Coverage

on:
    push:
        branches:
            - master
    pull_request:
        types: [opened, synchronize, reopened]

jobs:
    build:
        name: Build .NET Solution
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup .NET 9
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: "9.0.x"

            - name: Install coverlet console
              run: dotnet tool install --global coverlet.console

            - name: Install SonarScanner
              run: dotnet tool install --global dotnet-sonarscanner

            - name: Restore dependencies
              run: dotnet restore StreamHub.sln

            - name: Start Sonar scan
              run: |
                  dotnet sonarscanner begin \
                    /k:"Janobob_StreamHub" \
                    /o:"janobob" \
                    /n:"StreamHub" \
                    /d:sonar.token="${{ secrets.SONAR_TOKEN }}" \
                    /d:sonar.cs.opencover.reportsPaths="coverage.xml" \
                    /d:sonar.verbose="true"

            - name: Build Solution
              run: dotnet build StreamHub.sln --configuration Release --no-restore

            - name: Run Coverlet for Tests
              run: |
                  coverlet ./tests/StreamHub.Common.Tests/bin/Release/net9.0/StreamHub.Common.Tests.dll \
                    --target "dotnet" \
                    --targetargs "test ./tests/StreamHub.Common.Tests/StreamHub.Common.Tests.csproj --no-build" \
                    -f=opencover \
                    -o="coverage.xml"

            - name: End Sonar scan
              run: dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
