name: .NET Build

on:
    push:
        branches:
            - master
    pull_request:
        types: [opened, synchronize, reopened]

jobs:
    build:
        name: Build .NET Solution
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup .NET 9
              uses: actions/setup-dotnet@v4
              with:
                  dotnet-version: "9.0.x"

            - name: Restore dependencies
              run: dotnet restore StreamHub.sln

            - name: Build Solution
              run: dotnet build StreamHub.sln --configuration Release --no-restore

            - name: Run Tests
              run: dotnet test StreamHub.sln --configuration Release --no-build --verbosity normal

            # - name: SonarScanner for .NET 9
            #   uses: highbyte/sonarscan-dotnet@v2.4.2
            #   with:
            #       sonarProjectKey: Janobob_StreamHub
            #       sonarProjectName: StreamHub
            #       sonarOrganization: janobob
            #       dotnetTestArguments: /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
            #       sonarBeginArguments: /d:sonar.verbose="true" /d:sonar.language="cs" /d:sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml"

            #   env:
            #       SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
            #       GITHUB_TOKEN: ${{ secrets.TOKEN }}
