name: .NET Build

on:
    push:
        branches:
            - master
    pull_request:
        types: [opened, synchronize, reopened]

jobs:
    build:
        name: Build .NET Solution
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup .NET
              uses: actions/setup-dotnet@v3
              with:
                  dotnet-version: "9.0.x"

            - name: Restore dependencies
              run: dotnet restore StreamHub.sln

            - name: Build Solution
              run: dotnet build StreamHub.sln --configuration Release --no-restore

            - name: Run Tests
              run: dotnet test StreamHub.sln --configuration Release --no-build --verbosity normal --coverage --coverage-output-format xml --coverage-output coverage.xml

            - name: SonarScanner for .NET 9
              uses: highbyte/sonarscan-dotnet@v2.4.2
              with:
                  sonarProjectKey: Janobob_StreamHub
                  sonarProjectName: StreamHub
                  sonarOrganization: janobob
              env:
                  SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
                  GITHUB_TOKEN: ${{ secrets.TOKEN }}
