name: SonarCloud Test Coverage

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  angular-sonar:
    name: SonarCloud Test Coverage Angular
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
          cache-dependency-path: "**/package-lock.json"

      - name: Install dependencies
        run: npm ci
        working-directory: "StreamHub.Web"

      - name: Run Unit Tests with Coverage
        run: npm run test -- --watch=false --code-coverage --browsers=ChromeHeadless
        working-directory: "StreamHub.Web"

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v2
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          projectBaseDir: "StreamHub.Web"
          args: >
            -Dsonar.projectKey=Janobob_StreamHub
            -Dsonar.organization=janobob
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
